# Generated by Django 5.2 on 2025-05-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('wishlist', 'Пожелание'), ('problem', 'Проблема'), ('claim', 'Претензия'), ('other', 'Другое')], max_length=20)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='feedback_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
